image: node:12.17.0

stages:
  - build
  - deploy
#
# test:
#   stage: test
#   image: alekzonder/puppeteer
#   variables:
#     HEADLESS: 'true'
#   script:
#     - cd tests
#     - npm install
#     - ./node_modules/codeceptjs/bin/codecept.js run --debug --steps
#   artifacts:
#     expire_in: 1 week
#     when: always
#     paths:
#       - tests/output
.pages_base: &pages_base
  script:
    - npm install
    - node ./node_modules/documentation/bin/documentation.js build index.js -f html -o public
  artifacts:
    paths:
      - public

pages_branch:
  <<: *pages_base
  stage: build
  except:
    - master

pages:
  stage: deploy
  <<: *pages_base
  only:
    - master
